# Set base image (host OS)
FROM python:3.11-slim-bookworm 

# Set the working directory in the container
WORKDIR /app

# Copy the dependencies file to the working directory
COPY requirementsSyncStories.txt .

# Install any dependencies
RUN pip install -r requirementsSyncStories.txt --upgrade

# Install dependencies
RUN apt update && apt install -y curl

# Copy the source code into the container.
COPY . .

CMD ["python", "sync-stories.py"]
